# Generated by Django 2.0 on 2018-01-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
