# Generated by Django 2.0 on 2018-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auth_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
